name: CD

on:
  push:
    branches:
      - CD

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
    - name: Checkout Test
      uses: actions/checkout@v2
    - name: Set ssh key
      run: |
        mkdir -p ~/.ssh && \
        echo "$ssh_key" | base64 -d > ~/.ssh/id_rsa && \
        chmod 0600 ~/.ssh/id_rsa
    - name: Создание папки с именем в домашней директории
      run: ssh bdb2c2023q4_guest_3@brain-client.bigdatateam.org "mkdir ~/Danaisk"

    - name: Создание файла task41.txt
      run: ssh bdb2c2023q4_guest_3@brain-client.bigdatateam.org "touch ~/Danaisk/task41.txt"
      